#!/usr/bin/env bash
# spawn-agent.sh — start a long-running Claude agent that outlives IDE disconnects.
#
# The agent runs under the Maestro tmux server, whose parent is init (PID 1),
# so it is NOT a child of the Cursor/VS Code extension host. Closing the IDE,
# hibernating, or dropping the network leaves it running.
#
# Defaults to Opus 5. These agents run unattended, which is the worst place to
# silently get a weaker model: Maestro's session default is Sonnet 5, and its
# bundled Claude Code predates Opus 5 so /model does not even list it -- but the
# CLI forwards an explicit --model string to the API just fine.
#
# THE ROLE. The agent runs with ORCH_ROLE=worker on its command line, so
# CLAUDE.md sends it to orchestration/WORKER.md whoever started it: the
# orchestrator's own ORCH_ROLE=orchestrator does not reach it (30 September).
#
# Usage:  scripts/spawn-agent.sh <name> <task-file> [extra claude args...]
# Example: scripts/spawn-agent.sh refactor .maestro/tasks/refactor.md
#          scripts/spawn-agent.sh cheap .maestro/tasks/cheap.md --model claude-sonnet-5

set -euo pipefail

SOCKET="${MAESTRO_TMUX_SOCKET:-/tmp/tmux-shared/maestro.sock}"
LOG_DIR="${SPAWN_AGENT_LOG_DIR:-/workspace/.maestro/logs}"
RUN_DIR="${SPAWN_AGENT_RUN_DIR:-/workspace/.maestro/run}"
WORKDIR="${SPAWN_AGENT_CWD:-$PWD}"
MODEL="${SPAWN_AGENT_MODEL:-claude-opus-5}"

die() { printf 'spawn-agent: %s\n' "$1" >&2; exit 1; }

[ $# -ge 2 ] || die "usage: $(basename "$0") <name> <task-file> [extra claude args...]"

name=$1; task_file=$2; shift 2

[[ "$name" =~ ^[A-Za-z0-9._-]+$ ]] || die "name must be [A-Za-z0-9._-], got: $name"
[ -r "$task_file" ] || die "task file not readable: $task_file"
command -v tmux   >/dev/null || die "tmux not found"
command -v claude >/dev/null || die "claude not found"

# Absolute, so the runner is independent of where it is invoked from.
task_abs=$(cd "$(dirname "$task_file")" && pwd)/$(basename "$task_file")

session="agent-$name"
if tmux -S "$SOCKET" has-session -t "$session" 2>/dev/null; then
    die "session '$session' already running -- pick another name or kill it:
  tmux -S $SOCKET kill-session -t $session"
fi

mkdir -p "$LOG_DIR" "$RUN_DIR"
log="$LOG_DIR/$name.jsonl"
status="$RUN_DIR/$name.status"
runner="$RUN_DIR/$name.sh"

# Only inject --model when the caller did not supply one, to avoid a duplicate flag.
model_shown="$MODEL"
model_arg="--model $MODEL "
for a in "$@"; do
    case "$a" in
        --model|--model=*) model_arg=""; model_shown="(caller-supplied)" ;;
    esac
done

# %q-quote passthrough args so they survive embedding in the runner.
extra=""
[ $# -gt 0 ] && extra=$(printf '%q ' "$@")

# Unquoted heredoc: $log/$status/$task_abs/$model_arg/$extra expand NOW; \$? at run time.
cat > "$runner" <<EOF
#!/usr/bin/env bash
# Generated by spawn-agent.sh -- safe to read, edit, or delete.
# No 'set -e': we must record the exit code even when claude fails.
set -uo pipefail

printf 'running\tpid=%s\tstarted=%s\n' "\$\$" "\$(date -Is)" > "$status"

ORCH_ROLE=worker claude -p "\$(cat "$task_abs")" \
    $model_arg--dangerously-skip-permissions \
    --output-format stream-json --verbose \
    $extra>> "$log" 2>&1
rc=\$?

printf 'finished\texit=%s\tended=%s\n' "\$rc" "\$(date -Is)" > "$status"
EOF
chmod +x "$runner"

tmux -S "$SOCKET" new-session -d -s "$session" -c "$WORKDIR" "$runner"

cat <<EOF
started detached agent '$session'
  model   $model_shown
  task    $task_abs
  log     $log
  status  $status
  runner  $runner

check on it
  cat $status
  tail -n 20 $log
attach to its console
  tmux -S $SOCKET attach -t $session      # Ctrl-b d to detach
stop it
  tmux -S $SOCKET kill-session -t $session
EOF
